flowchart LR
 subgraph HatchMechanism[" "]
        E["RollingHatch opens and package falls down"]
        F["Hatch closes again"]
        H["Open hatch to take out the package"]
        G{"Is the open-button in the app pressed?"}
  end
    A["Camera at the door"] --> B{"AI detection: Is there a package?"}
    B -- Yes --> C["Send notification with photo to Smartapp"]
    C --> E
    E --> F
    F --> G
    G -- Yes --> H
    B -- No --> I["No action, wait"]

