mindmap
  root((SmartPackageBox))
    MainController
      Main Loop
      AI Detection
      Hatch Control
    MainFunctions
      Notification
      Picture Handling
      API Update
    AI
      Inference
      Response Handling
    MotorController
      Hatch Properties
      Move Hatch
    Api
      API Server
      Endpoints
    ImageServer
      Static File Server
    CameraFeed
      Take Picture
      Save Image
    Ntfy
      Send Notification
    NonSpecific
      Error Handling
      Logging
    FileModifyDLL
      File Operations